
/**
 * A small "Hello world" like beginner JAVA project generated by BlueJ. 
 * This was written in ~ 10 minutes, so it's a mess.
 * @author ann0see
 * @version 0.1
 */
public class PiCalc
{
    public PiCalc()
    { // calculate Pi (quite similar to https://meinstein.ch/math/berechnung-von-pi-annaeherung/)
      int numInside = 0;
      
      for (int i = 0; i<=4999;i++) { // 5000 runs gives us some percision (better than doing it manually only 50 times)
         double d = Math.sqrt(Math.pow(uniqueDouble(),2) + Math.pow(uniqueDouble(),2)); // calculate length; check if bigger than or lower than 1 to check if point is in/outside
         if (d < 1) {
               // point is inside
               numInside++;
               System.out.println("d: " + d + " is inside");
         } else {
               System.out.println("d: " + d + " is outside");
         }
      }
      
      System.out.println("There are " + numInside + " points inside");
      System.out.println("Pi: 4*numInside/5000: " + (4*numInside)/5000.0 + "!");
    }

    
    public double uniqueDouble()
    {        
        return Math.random(); // we might want to check if this double already existed. This might be possible by putting all previous numbers in an array. Afterwards, we check if the random double we generated already existed. 
    }
}
